version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - .:/var/www/html:cached
    command: php -S 0.0.0.0:8080 public/index.php
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_NAME:-loan_application}
      - MYSQL_USER=${DB_USERNAME:-mysql_user}
      - MYSQL_PASSWORD=${DB_USERNAME:-mysql_password}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSSWORD:-root_password}
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - loan_data:/var/lib/mysql:delegated
    ports:
      - 3306:3306
volumes:
  loan_data:
